version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: 'shouts.dev/laravel'
        container_name: shouts-laravel-app
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-shouts
        depends_on:
            - mysql
    mysql:
        image: 'mariadb:10'
        container_name: shouts-laravel-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: 'secret_root'
            MYSQL_PASSWORD: 'secret_tutorial'
            MYSQL_USER: 'user_tutorial'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./database/dbdata:/var/lib/mysql
        networks:
            - laravel-shouts

networks:
    laravel-shouts:
        driver: bridge